<?php

return [
	'knowledge_version' => '1.1.0',
	'updated_at'        => '2026-09-15',
	'topics'            => [
		[
			'id'          => 'capabilities',
			'title'       => 'Assistant capabilities and boundaries',
			'keywords'    => [ 'available', 'cannot', 'feature request', 'webmaster' ],
			'screen_ids'  => [],
			'post_types'  => [],
			'status'      => 'limited',
			'admin_page'  => null,
			'topic_file'  => 'capabilities.md',
		],
		[
			'id'          => 'getting-started',
			'title'       => 'Where website content is managed',
			'keywords'    => [ 'start', 'where', 'find', 'change', 'edit website', 'dashboard', 'wordpress', 'which screen', 'new here', 'content map' ],
			'screen_ids'  => [ 'dashboard' ],
			'post_types'  => [],
			'status'      => 'available',
			'admin_page'  => null,
			'topic_file'  => 'getting-started.md',
		],
		[
			'id'          => 'safe-editing-recovery',
			'title'       => 'Safe editing, revisions, trash, and recovery',
			'keywords'    => [ 'undo', 'restore', 'revision', 'revisions', 'autosave', 'lost', 'recover', 'trash', 'deleted', 'mistake', 'rollback', 'safe change' ],
			'screen_ids'  => [ 'page', 'edit-page', 'post', 'edit-post' ],
			'post_types'  => [ 'page', 'post' ],
			'status'      => 'limited',
			'admin_page'  => null,
			'topic_file'  => 'safe-editing-recovery.md',
		],
		[
			'id'          => 'publishing-checklist',
			'title'       => 'Pre-publish website quality checklist',
			'keywords'    => [ 'ready', 'check', 'checklist', 'before publish', 'quality', 'review', 'proofread', 'mobile', 'accessibility', 'links', 'launch' ],
			'screen_ids'  => [ 'page', 'post' ],
			'post_types'  => [ 'page', 'post' ],
			'status'      => 'available',
			'admin_page'  => null,
			'topic_file'  => 'publishing-checklist.md',
		],
		[
			'id'          => 'help-privacy-history',
			'title'       => 'Website Help context, privacy, and conversation history',
			'keywords'    => [ 'chat', 'history', 'privacy', 'context', 'read page', 'unsaved', 'conversation', 'delete chat', 'pin', 'rename', 'who can see', 'openai', 'stored' ],
			'screen_ids'  => [ 'toplevel_page_sz-website-help' ],
			'post_types'  => [],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'admin_page', 'slug' => 'sz-website-help' ],
			'topic_file'  => 'help-privacy-history.md',
		],
		[
			'id'          => 'galleries',
			'title'       => 'Gallery Library and gallery pages',
			'keywords'    => [ 'gallery', 'galleries', 'name', 'naming', 'rename', 'photos', 'images', 'reusable', 'order', 'caption', 'columns', 'shared gallery' ],
			'screen_ids'  => [ 'edit-sz_gallery', 'sz_gallery' ],
			'post_types'  => [ 'sz_gallery' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'post_type', 'post_type' => 'sz_gallery' ],
			'topic_file'  => 'galleries.md',
		],
		[
			'id'          => 'page-editor',
			'title'       => 'Pages and content blocks',
			'keywords'    => [ 'page', 'section', 'find', 'locate', 'edit', 'acf', 'title', 'slug', 'url', 'parent', 'container only', 'venue', 'primary service', 'page settings' ],
			'screen_ids'  => [ 'page', 'edit-page' ],
			'post_types'  => [ 'page' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'post_type', 'post_type' => 'page' ],
			'topic_file'  => 'page-editor.md',
		],
		[
			'id'          => 'page-blocks',
			'title'       => 'Page block reference',
			'keywords'    => [ 'block', 'layout', 'hero', 'text', 'image', 'services', 'pillars', 'faq', 'form', 'pricing', 'gallery', 'buttons', 'instagram', 'blog posts', 'heading level', 'spacing', 'columns' ],
			'screen_ids'  => [ 'page' ],
			'post_types'  => [ 'page' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'post_type', 'post_type' => 'page' ],
			'topic_file'  => 'page-blocks.md',
		],
		[
			'id'          => 'publishing-preview',
			'title'       => 'Previewing, publishing, and duplicating pages',
			'keywords'    => [ 'preview', 'publish', 'update', 'draft', 'duplicate', 'copy page', 'save', 'autosave', 'public', 'refresh preview', 'live preview' ],
			'screen_ids'  => [ 'page', 'edit-page', 'post', 'edit-post' ],
			'post_types'  => [ 'page', 'post' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'post_type', 'post_type' => 'page' ],
			'topic_file'  => 'publishing-preview.md',
		],
		[
			'id'          => 'media',
			'title'       => 'Media Library, folders, and image details',
			'keywords'    => [ 'media', 'upload', 'photo', 'image', 'folder', 'alt text', 'caption', 'metadata', 'duplicate image', 'delete image', 'crop', 'copyright', 'licence' ],
			'screen_ids'  => [ 'upload', 'attachment', 'edit-sz_media_folder' ],
			'post_types'  => [ 'attachment' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'admin_path', 'path' => 'upload.php' ],
			'topic_file'  => 'media.md',
		],
		[
			'id'          => 'menus',
			'title'       => 'Navigation and site menus',
			'keywords'    => [ 'menu', 'navigation', 'header', 'dropdown', 'site menu', 'menu override', 'unassigned pages', 'navigation label', 'wrong header', 'add link', 'remove link' ],
			'screen_ids'  => [ 'nav-menus', 'appearance_page_sz-site-menu-manager' ],
			'post_types'  => [ 'page' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'admin_path', 'path' => 'themes.php?page=sz-site-menu-manager' ],
			'topic_file'  => 'menus.md',
		],
		[
			'id'          => 'blog-posts',
			'title'       => 'Blog posts and categories',
			'keywords'    => [ 'post', 'blog', 'article', 'category', 'featured image', 'add button', 'excerpt', 'reading time', 'post listing', 'blog grid' ],
			'screen_ids'  => [ 'post', 'edit-post', 'edit-category' ],
			'post_types'  => [ 'post' ],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'post_type', 'post_type' => 'post' ],
			'topic_file'  => 'blog-posts.md',
		],
		[
			'id'          => 'forms',
			'title'       => 'Forms and enquiry delivery',
			'keywords'    => [ 'form', 'contact', 'enquiry', 'field', 'field id', 'form id', 'email', 'customer copy', 'delivery', 'vsco', 'required', 'submit', 'submission failed', 'options' ],
			'screen_ids'  => [ 'page' ],
			'post_types'  => [ 'page' ],
			'status'      => 'limited',
			'admin_page'  => [ 'type' => 'post_type', 'post_type' => 'page' ],
			'topic_file'  => 'forms.md',
		],
		[
			'id'          => 'site-settings',
			'title'       => 'Site settings, footer, and public business details',
			'keywords'    => [ 'site settings', 'global', 'shared', 'footer', 'copyright', 'social links', 'business', 'photographer', 'services', 'service key', 'address', 'award', 'structured data' ],
			'screen_ids'  => [ 'settings_page_sz-site-settings' ],
			'post_types'  => [],
			'status'      => 'available',
			'admin_page'  => [ 'type' => 'admin_page', 'slug' => 'site-settings' ],
			'topic_file'  => 'site-settings.md',
		],
		[
			'id'          => 'seo',
			'title'       => 'SEO, social previews, and searchability audit',
			'keywords'    => [ 'seo', 'search', 'google', 'index', 'ranking', 'social', 'facebook', 'cache', 'title', 'description', 'audit', 'h1', 'metadata', 'structured data', 'rich result' ],
			'screen_ids'  => [ 'toplevel_page_sz-social-seo-manager' ],
			'post_types'  => [ 'page' ],
			'status'      => 'limited',
			'admin_page'  => [ 'type' => 'admin_page', 'slug' => 'sz-social-seo-manager' ],
			'topic_file'  => 'seo.md',
		],
		[
			'id'          => 'troubleshooting',
			'title'       => 'Troubleshooting WordPress editing',
			'keywords'    => [ 'problem', 'broken', 'missing', 'not showing', 'cannot save', 'error', 'stuck', 'help', 'old preview', 'wrong header', 'delivery failed', 'input limit' ],
			'screen_ids'  => [],
			'post_types'  => [],
			'status'      => 'limited',
			'admin_page'  => null,
			'topic_file'  => 'troubleshooting.md',
		],
		[
			'id'          => 'unsupported-features',
			'title'       => 'Features not available in this website',
			'keywords'    => [ 'booking', 'appointments', 'shop', 'ecommerce', 'payments', 'customer account', 'newsletter', 'automation', 'install plugin', 'do it for me' ],
			'screen_ids'  => [],
			'post_types'  => [],
			'status'      => 'not_available',
			'admin_page'  => null,
			'topic_file'  => 'unsupported-features.md',
		],
	],
];