import { useEffect, useState } from 'react'
import type { LoaderFunctionArgs, MetaFunction } from 'react-router'
import { useLoaderData } from 'react-router'
import BlockRenderer from '~/components/blocks/BlockRenderer'
import RichText from '~/components/RichText'
import { stripSensitiveFormBlockData } from '~/lib/forms'
import { stripHtml } from '~/lib/html'
import { getPostsByCategories, getPreviewPage } from '~/lib/wordpress'
import type { BlogPostsData, WPPage } from '~/types/wordpress'
import styles from './preview.module.scss'

// ─── Types ────────────────────────────────────────────────────────────────────
interface PreviewLoaderData {
  page: WPPage
  isIframe: boolean
  blogPostsData?: BlogPostsData
}

interface DraftPreviewMessage {
  source: 'sz-editor'
  action: 'preview-state'
  page?: Partial<WPPage>
}

function mergeRenderedField(
  base: WPPage['title'] | WPPage['content'] | WPPage['excerpt'],
  override?: Partial<WPPage['title']> | Partial<WPPage['content']> | Partial<WPPage['excerpt']>,
) {
  if (!override) return base
  return {
    ...base,
    ...override,
  }
}

function mergePreviewPage(base: WPPage, override?: Partial<WPPage>): WPPage {
  if (!override) return base

  return {
    ...base,
    ...override,
    title: mergeRenderedField(base.title, override.title),
    content: mergeRenderedField(base.content, override.content),
    excerpt: mergeRenderedField(base.excerpt, override.excerpt),
    acf: override.acf ? { ...base.acf, ...override.acf } : base.acf,
    yoast_head_json: override.yoast_head_json
      ? { ...base.yoast_head_json, ...override.yoast_head_json }
      : base.yoast_head_json,
  }
}

async function fetchPreviewBlogPosts(page: WPPage): Promise<BlogPostsData | undefined> {
  const blogBlock = page.acf?.blocks?.find((block) => block.acf_fc_layout === 'blog_posts')
  if (!blogBlock) return undefined

  const perPage = blogBlock.posts_per_page ?? 6
  const categories = Array.isArray(blogBlock.categories) ? blogBlock.categories : []
  const params = new URLSearchParams({
    page: '1',
    per_page: String(perPage),
  })

  if (categories.length > 0) {
    params.set('categories', categories.join(','))
  }

  try {
    const res = await fetch(`/api/blog-posts?${params.toString()}`, {
      headers: { Accept: 'application/json' },
    })
    if (!res.ok) return undefined
    return (await res.json()) as BlogPostsData
  } catch {
    return undefined
  }
}

// ─── Loader ───────────────────────────────────────────────────────────────────
// WordPress preview links (generated by the sz-headless mu-plugin) point here:
//   /preview?id=<post_id>&secret=<shared_secret>
//   /preview?id=<post_id>&secret=<shared_secret>&iframe=true  (embedded in WP editor)
//
// The loader calls back to the WP REST API to fetch the latest draft content.
export async function loader({ request }: LoaderFunctionArgs): Promise<PreviewLoaderData> {
  const url = new URL(request.url)
  const id = url.searchParams.get('id')
  const secret = url.searchParams.get('secret') ?? process.env.PREVIEW_SECRET ?? ''
  const isIframe = url.searchParams.get('iframe') === 'true'

  if (!id) throw new Response('Missing preview id', { status: 400 })

  const page = await getPreviewPage(Number(id), secret)
  if (!page) throw new Response('Preview not found or secret invalid', { status: 404 })

  const publicPage = stripSensitiveFormBlockData(page)

  // If the page has a blog_posts block, pre-fetch posts for preview
  let blogPostsData: BlogPostsData | undefined
  const blogBlock = publicPage.acf?.blocks?.find((b) => b.acf_fc_layout === 'blog_posts')
  if (blogBlock) {
    const perPage =
      'posts_per_page' in blogBlock ? (blogBlock.posts_per_page ?? 6) : 6
    const categoryIds =
      'categories' in blogBlock && Array.isArray(blogBlock.categories)
        ? blogBlock.categories
        : []
    blogPostsData = await getPostsByCategories(categoryIds, 1, perPage)
  }

  return { page: publicPage, isIframe, blogPostsData }
}

export const meta: MetaFunction<typeof loader> = ({ data }) => {
  if (!data) return [{ title: 'Preview | Studio Zanetti' }]
  const pageTitle = stripHtml(data.page.title.rendered)
  return [
    { title: `Preview: ${pageTitle} | Studio Zanetti` },
    { name: 'robots', content: 'noindex, nofollow' },
  ]
}

// ─── Route component ──────────────────────────────────────────────────────────
const PreviewPage = () => {
  const loaderData = useLoaderData<typeof loader>()
  const { page, isIframe, blogPostsData } = loaderData
  const [draftPageOverride, setDraftPageOverride] = useState<Partial<WPPage> | null>(null)
  const [draftBlogPostsData, setDraftBlogPostsData] = useState<BlogPostsData | undefined>(
    undefined,
  )
  const [basePageId, setBasePageId] = useState(page.id)

  if (basePageId !== page.id) {
    setBasePageId(page.id)
    setDraftPageOverride(null)
    setDraftBlogPostsData(undefined)
  }

  const currentPage = mergePreviewPage(page, draftPageOverride ?? undefined)
  const currentBlogPostsData = draftBlogPostsData ?? blogPostsData

  useEffect(() => {
    const handlePreviewMessage = (event: MessageEvent<DraftPreviewMessage>) => {
      if (event.data?.source !== 'sz-editor' || event.data?.action !== 'preview-state') return

      setDraftPageOverride(event.data.page ?? null)

      const mergedPage = mergePreviewPage(page, event.data.page)

      void fetchPreviewBlogPosts(mergedPage).then((data) => {
        setDraftBlogPostsData(data)
      })
    }

    window.addEventListener('message', handlePreviewMessage)
    window.parent?.postMessage({ source: 'sz-preview', action: 'ready-for-state' }, '*')
    window.opener?.postMessage({ source: 'sz-preview', action: 'ready-for-state' }, '*')

    return () => {
      window.removeEventListener('message', handlePreviewMessage)
    }
  }, [page])

  const blocks = currentPage.acf?.blocks

  return (
    <div className={styles.previewWrapper}>
      {/* Hide the preview banner when embedded in the WordPress editor iframe */}
      {!isIframe && (
        <div className={styles.previewBanner} role="status">
          <p>
            <strong>Preview Mode</strong> — You are viewing a draft. This page is not publicly
            visible.
          </p>
        </div>
      )}

      {blocks?.length ? (
        <BlockRenderer
          blocks={blocks}
          interactive={isIframe}
          blogPostsData={currentBlogPostsData}
        />
      ) : (
        <div className={styles.page}>
          <header className={styles.pageHeader}>
            <h1 className={styles.pageTitle}>{stripHtml(currentPage.title.rendered)}</h1>
          </header>
          <div className={styles.pageContent}>
            <RichText html={currentPage.content.rendered} />
          </div>
        </div>
      )}
    </div>
  )
}

export default PreviewPage
