import type { LoaderFunctionArgs, MetaFunction } from 'react-router'
import { useLoaderData } from 'react-router'
import BlockRenderer from '~/components/blocks/BlockRenderer'
import RichText from '~/components/RichText'
import { stripSensitiveFormBlockData } from '~/lib/forms'
import { stripHtml } from '~/lib/html'
import { getPostsByCategories, getPreviewPage } from '~/lib/wordpress'
import type { BlogPostsData, WPPage } from '~/types/wordpress'
import styles from './preview.module.scss'

// ─── Types ────────────────────────────────────────────────────────────────────
interface PreviewLoaderData {
  page: WPPage
  isIframe: boolean
  blogPostsData?: BlogPostsData
}

// ─── Loader ───────────────────────────────────────────────────────────────────
// WordPress preview links (generated by the sz-headless mu-plugin) point here:
//   /preview?id=<post_id>&secret=<shared_secret>
//   /preview?id=<post_id>&secret=<shared_secret>&iframe=true  (embedded in WP editor)
//
// The loader calls back to the WP REST API to fetch the latest draft content.
export async function loader({ request }: LoaderFunctionArgs): Promise<PreviewLoaderData> {
  const url = new URL(request.url)
  const id = url.searchParams.get('id')
  const secret = url.searchParams.get('secret') ?? process.env.PREVIEW_SECRET ?? ''
  const isIframe = url.searchParams.get('iframe') === 'true'

  if (!id) throw new Response('Missing preview id', { status: 400 })

  const page = await getPreviewPage(Number(id), secret)
  if (!page) throw new Response('Preview not found or secret invalid', { status: 404 })

  const publicPage = stripSensitiveFormBlockData(page)

  // If the page has a blog_posts block, pre-fetch posts for preview
  let blogPostsData: BlogPostsData | undefined
  const blogBlock = publicPage.acf?.blocks?.find((b) => b.acf_fc_layout === 'blog_posts')
  if (blogBlock) {
    const perPage =
      'posts_per_page' in blogBlock ? (blogBlock.posts_per_page ?? 6) : 6
    const categoryIds =
      'categories' in blogBlock && Array.isArray(blogBlock.categories)
        ? blogBlock.categories
        : []
    blogPostsData = await getPostsByCategories(categoryIds, 1, perPage)
  }

  return { page: publicPage, isIframe, blogPostsData }
}

export const meta: MetaFunction<typeof loader> = ({ data }) => {
  if (!data) return [{ title: 'Preview | Studio Zanetti' }]
  const pageTitle = stripHtml(data.page.title.rendered)
  return [
    { title: `Preview: ${pageTitle} | Studio Zanetti` },
    { name: 'robots', content: 'noindex, nofollow' },
  ]
}

// ─── Route component ──────────────────────────────────────────────────────────
const PreviewPage = () => {
  const { page, isIframe, blogPostsData } = useLoaderData<typeof loader>()
  const blocks = page.acf?.blocks

  return (
    <div className={styles.previewWrapper}>
      {/* Hide the preview banner when embedded in the WordPress editor iframe */}
      {!isIframe && (
        <div className={styles.previewBanner} role="status">
          <p>
            <strong>Preview Mode</strong> — You are viewing a draft. This page is not publicly
            visible.
          </p>
        </div>
      )}

      {blocks?.length ? (
        <BlockRenderer blocks={blocks} interactive={isIframe} blogPostsData={blogPostsData} />
      ) : (
        <div className={styles.page}>
          <header className={styles.pageHeader}>
            <h1 className={styles.pageTitle}>{stripHtml(page.title.rendered)}</h1>
          </header>
          <div className={styles.pageContent}>
            <RichText html={page.content.rendered} />
          </div>
        </div>
      )}
    </div>
  )
}

export default PreviewPage
